### PR TITLE
Dove Support

### PR DESCRIPTION
**Pull request by forgot**
- [x] Tell us about the problem your pull request is solving.
Updates `@feathersjs` dependencies to `^5.0.0-pre.3` to work with Dove
- [x] Are there any open issues that are related to this?
Not that I could find
- [x] Is this PR dependent on PRs in other repos?
Nope!

This pull request primarily updates the type expectations to match Dove. It would obviously be better for this to remain it's own branch and did not merge with `master`, but there is not currently a Dove branch.

All tests pass with `npm test`

### CODE REVIEW

**Review by mrhegemon — APPROVED** [review]

**Comment by daffl** [comment]
Great, thank you for doing that! I'm wondering if I should move the `Paginated` type back into the main repo if that is the only breaking change (which it looks like it is).

**Comment by forgot** [comment]
I'm happy to pull the changes in if you do. Out of curiosity, what was the reason for moving it in the first place?

**Comment by daffl** [comment]
Well, the type isn't really something a core Feathers service expects or uses, it's only a convention used by the adapters. I just published `5.0.0-pre.4` changing it back. I think most things should now be backwards compatible but it'd probably be good to pass the new generic types along so you can initialize the adapter service with data and return types other than `any`.

**Comment by forgot** [comment]
I've bumped everything to `5.0.0-pre.4` and moved the `Paginated` import back. All tests are still passing.

**Comment by forgot** [comment]
I've bumped everything to 5.0.0-pre.9, and all tests are still passing.

**Comment by daffl** [comment]
This is good to know. At least updating the adapters (other than infrastructure) should be doable then. I had to make a bunch of dud pre-releases because the publish was broken so I didn't expect too much to change.

**Comment by forgot** [comment]
I've bumped everything to 5.0.0-pre.16, and all tests are still passing.

**Comment by fratzinger** [comment]
merged via #400 into master. `feathers-sequelize@7.0.0` released with dove support.
Thanks for kicking this off!

**Pull request closed without merging**
