### PR TITLE
Docs: improve instruction for setting the 'dialect' variable

### PR DESCRIPTION
**Pull request by bravo-kernel**
As a novice it wasn't clear to me that the `dialect` variable in the code example needs to be updated. This note would have helped me and would have prevented an error.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the pull request. Could you clarify a little more what this note means?

**Comment by bravo-kernel** [comment]
Of the four dialects shown in the example only must remain or an error will be thrown stating something like “as of version 4 dialect must be stated explicitely”. Sorry but can’t be exact atm, I am on the road.

After I figured it out I realized I should probably have taken the OR characters literally |

**Comment by daffl** [comment]
Oh, I think then the docs should be updated to change

```js
const dialect = 'mysql'|'sqlite'|'postgres'|'mssql';
```

To

```js
const dialect = 'postgres'; // Or your dialect name
```

The original code is valid JavaScript but doesn't make any sense anyway.

**Comment by bravo-kernel** [comment]
Great improvent, I will update the PR using your example.

**Comment by bravo-kernel** [comment]
@daffl changed and rebased as requested 👍

**Comment by daffl** [comment]
Thank you!

**Pull request merged**
